CREATE TABLE grades (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name VARCHAR2(100) NOT NULL,
    subject VARCHAR2(100) NOT NULL,
    grade NUMBER CHECK (grade >= 0 AND grade <= 100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO grades (student_name, subject, grade) VALUES ('John Doe', 'Mathematics', 85);
INSERT INTO grades (student_name, subject, grade) VALUES ('Jane Smith', 'Science', 90);
INSERT INTO grades (student_name, subject, grade) VALUES ('Alice Johnson', 'History', 78);
INSERT INTO grades (student_name, subject, grade) VALUES ('Bob Brown', 'Literature', 92);